# Generated by Django 6.0 on 2025-12-20 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('one_month_price_before_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('one_month_price_after_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('six_month_price_before_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('six_month_price_after_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('twelve_month_price_before_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('twelve_month_price_after_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='packages.package')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('1_month', '1 Month'), ('6_months', '6 Months'), ('12_months', '12 Months')], max_length=20)),
                ('price_before_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_after_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fullname', models.CharField(max_length=255)),
                ('whatsapp_phone_number', models.CharField(max_length=20)),
                ('calls_phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_received', 'Payment Received'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('whatsapp_sent_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp_message_sid', models.CharField(blank=True, max_length=100)),
                ('whatsapp_error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Coach notes')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='packages.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
