# Generated by Django 5.2.9 on 2025-12-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='one_month_price_after_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='1 Month Price After Discount'),
        ),
        migrations.AlterField(
            model_name='package',
            name='one_month_price_before_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='1 Month Price Before Discount'),
        ),
    ]
