# Generated by Django 5.2.9 on 2025-12-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_one_month_price_after_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='six_month_price_after_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='6 Months Price After Discount'),
        ),
        migrations.AlterField(
            model_name='package',
            name='six_month_price_before_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='6 Months Price Before Discount'),
        ),
        migrations.AlterField(
            model_name='package',
            name='twelve_month_price_after_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='12 Months Price After Discount'),
        ),
        migrations.AlterField(
            model_name='package',
            name='twelve_month_price_before_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='12 Months Price Before Discount'),
        ),
    ]
