# Generated by Django 5.2.9 on 2026-01-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_package_six_month_price_after_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
