# Generated by Django 5.2.9 on 2026-01-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_package_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='three_month_price_after_discount',
            field=models.DecimalField(decimal_places=2, default=550, max_digits=10, verbose_name='3 Months Price After Discount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='three_month_price_before_discount',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=10, verbose_name='3 Months Price Before Discount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.CharField(choices=[('1_month', '1 Month'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('12_months', '12 Months')], max_length=20),
        ),
    ]
