# Generated by Django 6.0 on 2025-12-20 18:13

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('before_image', models.ImageField(help_text='Maximum 5MB, recommended size 1200x1200px', upload_to='transformations/before/', validators=[users.models.validate_image_size, users.models.validate_image_dimensions])),
                ('after_image', models.ImageField(help_text='Maximum 5MB, recommended size 1200x1200px', upload_to='transformations/after/', validators=[users.models.validate_image_size, users.models.validate_image_dimensions])),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
