# Generated by Django 5.2.9 on 2026-01-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transformation',
            name='story',
            field=models.TextField(blank=True, help_text='Optional story about the transformation'),
        ),
    ]
